version: '3.7'

services:
  
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql-server
    platform: linux/x86_64
    container_name: my-mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql

    # these variables could be stored in an external .env file as well
    # w0090347 will automatically be set to full access to sean_dotnetcoreSamples
    environment:
      MYSQL_ROOT_PASSWORD: 1337
      MYSQL_DATABASE: NSCCACC
      MYSQL_USER: Trailblazer780
      MYSQL_PASSWORD: 1337
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: my-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    web-root:
      driver: local